params:
  iterations: 30
  dimensions: 50
  population: 50
  blue_population: 1000
  green_population: 1000
  red_population: 0
  satisfaction_rate: 30
  blue_satisfaction_rate: 30
  green_satisfaction_rate: 30
  red_satisfaction_rate: 30